name: Docker Image Tag

on:
  workflow_call:

jobs:
  generate-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Docker tag
        id: tag
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            echo "TAG_NAME=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          else
            echo "TAG_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

